<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-notifications',
	'deps' => [
		'elementor-v2-editor',
		'elementor-v2-store',
		'elementor-v2-ui',
		'react',
		'react-dom',
	],
];
