<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-styles-repository',
	'deps' => [
		'elementor-v2-editor-current-user',
		'elementor-v2-editor-elements',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-schema',
		'elementor-v2-utils',
		'react',
		'wp-i18n',
	],
];
