<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-wp-media',
	'deps' => [
		'elementor-v2-query',
		'elementor-v2-utils',
		'react',
	],
];
