<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor-site-navigation',
	'deps' => [
		'elementor-v2-editor-app-bar',
		'elementor-v2-editor-documents',
		'elementor-v2-editor-panels',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-env',
		'elementor-v2-icons',
		'elementor-v2-query',
		'elementor-v2-ui',
		'react',
		'wp-api-fetch',
		'wp-i18n',
	],
];
