<?php

// This file was autogenerated by tools/release/sync-stable-blocks.js, do not change manually!
// Returns folder names for static blocks necessary for core blocks registration.
return array(
	'accordion-heading',
	'accordion-panel',
	'audio',
	'buttons',
	'code',
	'column',
	'columns',
	'details',
	'embed',
	'freeform',
	'group',
	'html',
	'list-item',
	'math',
	'missing',
	'more',
	'nextpage',
	'paragraph',
	'preformatted',
	'pullquote',
	'quote',
	'separator',
	'social-links',
	'spacer',
	'table',
	'terms-query',
	'text-columns',
	'verse',
);
