<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-menus',
	'deps' => [
		'elementor-v2-locations',
		'react',
	],
];
