#!/bin/bash

set -x

set -eo pipefail

# When the custom image is run as a S2I builder we allow for the user to
# provide their own plugins, themes and languages directories. We need to
# stash these away and they will be applied only when the final application
# image is run so that they can be applied to what is contained in the
# persistent volume.




if [ ! -f "/opt/app-root/silo/wordpress/wp-config.php" ]; then

    cp /opt/app-root/src/wp-config-sample.php /opt/app-root/silo/wordpress/wp-config.php



else if [ ! -d "/opt/app-root/silo/wordpress/wp-content" ]; then

         cp /opt/app-root/src/wp-content /opt/app-root/silo/wordpress

else

fi


rm -fr /opt/app-root/silo/wordpress/*

mv /tmp/src/* /opt/app-root/silo/wordpress/

rm -rf /tmp/src

fix-permissions /opt/app-root
