<?php

/* Continent and city translations for timezone selection.
 * This file is not included anywhere. It exists solely for use by xgettext.
 */

__('Africa');
__('Abidjan');
__('Accra');
__('Addis Ababa');
__('Algiers');
__('Asmara');
__('Asmera');
__('Bamako');
__('Bangui');
__('Banjul');
__('Bissau');
__('Blantyre');
__('Brazzaville');
__('Bujumbura');
__('Cairo');
__('Casablanca');
__('Ceuta');
__('Conakry');
__('Dakar');
__('Dar es Salaam');
__('Djibouti');
__('Douala');
__('El Aaiun');
__('Freetown');
__('Gaborone');
__('Harare');
__('Johannesburg');
__('Kampala');
__('Khartoum');
__('Kigali');
__('Kinshasa');
__('Lagos');
__('Libreville');
__('Lome');
__('Luanda');
__('Lubumbashi');
__('Lusaka');
__('Malabo');
__('Maputo');
__('Maseru');
__('Mbabane');
__('Mogadishu');
__('Monrovia');
__('Nairobi');
__('Ndjamena');
__('Niamey');
__('Nouakchott');
__('Ouagadougou');
__('Porto-Novo');
__('Sao Tome');
__('Timbuktu');
__('Tripoli');
__('Tunis');
__('Windhoek');
__('America');
__('Adak');
__('Anchorage');
__('Anguilla');
__('Antigua');
__('Araguaina');
__('Argentina');
__('Buenos Aires');
__('Catamarca');
__('ComodRivadavia');
__('Cordoba');
__('Jujuy');
__('La Rioja');
__('Mendoza');
__('Rio Gallegos');
__('San Juan');
__('San Luis');
__('Tucuman');
__('Ushuaia');
__('Aruba');
__('Asuncion');
__('Atikokan');
__('Atka');
__('Bahia');
__('Barbados');
__('Belem');
__('Belize');
__('Blanc-Sablon');
__('Boa Vista');
__('Bogota');
__('Boise');
__('Cambridge Bay');
__('Campo Grande');
__('Cancun');
__('Caracas');
__('Cayenne');
__('Cayman');
__('Chicago');
__('Chihuahua');
__('Coral Harbour');
__('Costa Rica');
__('Cuiaba');
__('Curacao');
__('Danmarkshavn');
__('Dawson');
__('Dawson Creek');
__('Denver');
__('Detroit');
__('Dominica');
__('Edmonton');
__('Eirunepe');
__('El Salvador');
__('Ensenada');
__('Fort Wayne');
__('Fortaleza');
__('Glace Bay');
__('Godthab');
__('Goose Bay');
__('Grand Turk');
__('Grenada');
__('Guadeloupe');
__('Guatemala');
__('Guayaquil');
__('Guyana');
__('Halifax');
__('Havana');
__('Hermosillo');
__('Indiana');
__('Indianapolis');
__('Knox');
__('Marengo');
__('Petersburg');
__('Tell City');
__('Vevay');
__('Vincennes');
__('Winamac');
__('Inuvik');
__('Iqaluit');
__('Jamaica');
__('Juneau');
__('Kentucky');
__('Louisville');
__('Monticello');
__('Knox IN');
__('La Paz');
__('Lima');
__('Los Angeles');
__('Maceio');
__('Managua');
__('Manaus');
__('Marigot');
__('Martinique');
__('Mazatlan');
__('Menominee');
__('Merida');
__('Mexico City');
__('Miquelon');
__('Moncton');
__('Monterrey');
__('Montevideo');
__('Montreal');
__('Montserrat');
__('Nassau');
__('New York');
__('Nipigon');
__('Nome');
__('Noronha');
__('North Dakota');
__('Center');
__('New Salem');
__('Panama');
__('Pangnirtung');
__('Paramaribo');
__('Phoenix');
__('Port-au-Prince');
__('Port of Spain');
__('Porto Acre');
__('Porto Velho');
__('Puerto Rico');
__('Rainy River');
__('Rankin Inlet');
__('Recife');
__('Regina');
__('Resolute');
__('Rio Branco');
__('Rosario');
__('Santiago');
__('Santo Domingo');
__('Sao Paulo');
__('Scoresbysund');
__('Shiprock');
__('St Barthelemy');
__('St Johns');
__('St Kitts');
__('St Lucia');
__('St Thomas');
__('St Vincent');
__('Swift Current');
__('Tegucigalpa');
__('Thule');
__('Thunder Bay');
__('Tijuana');
__('Toronto');
__('Tortola');
__('Vancouver');
__('Virgin');
__('Whitehorse');
__('Winnipeg');
__('Yakutat');
__('Yellowknife');
__('Antarctica');
__('Casey');
__('Davis');
__('DumontDUrville');
__('Mawson');
__('McMurdo');
__('Palmer');
__('Rothera');
__('South Pole');
__('Syowa');
__('Vostok');
__('Arctic');
__('Longyearbyen');
__('Asia');
__('Aden');
__('Almaty');
__('Amman');
__('Anadyr');
__('Aqtau');
__('Aqtobe');
__('Ashgabat');
__('Ashkhabad');
__('Baghdad');
__('Bahrain');
__('Baku');
__('Bangkok');
__('Beirut');
__('Bishkek');
__('Brunei');
__('Calcutta');
__('Choibalsan');
__('Chongqing');
__('Chungking');
__('Colombo');
__('Dacca');
__('Damascus');
__('Dhaka');
__('Dili');
__('Dubai');
__('Dushanbe');
__('Gaza');
__('Harbin');
__('Ho Chi Minh');
__('Hong Kong');
__('Hovd');
__('Irkutsk');
__('Istanbul');
__('Jakarta');
__('Jayapura');
__('Jerusalem');
__('Kabul');
__('Kamchatka');
__('Karachi');
__('Kashgar');
__('Katmandu');
__('Kolkata');
__('Krasnoyarsk');
__('Kuala Lumpur');
__('Kuching');
__('Kuwait');
__('Macao');
__('Macau');
__('Magadan');
__('Makassar');
__('Manila');
__('Muscat');
__('Nicosia');
__('Novosibirsk');
__('Omsk');
__('Oral');
__('Phnom Penh');
__('Pontianak');
__('Pyongyang');
__('Qatar');
__('Qyzylorda');
__('Rangoon');
__('Riyadh');
__('Saigon');
__('Sakhalin');
__('Samarkand');
__('Seoul');
__('Shanghai');
__('Singapore');
__('Taipei');
__('Tashkent');
__('Tbilisi');
__('Tehran');
__('Tel Aviv');
__('Thimbu');
__('Thimphu');
__('Tokyo');
__('Ujung Pandang');
__('Ulaanbaatar');
__('Ulan Bator');
__('Urumqi');
__('Vientiane');
__('Vladivostok');
__('Yakutsk');
__('Yekaterinburg');
__('Yerevan');
__('Atlantic');
__('Azores');
__('Bermuda');
__('Canary');
__('Cape Verde');
__('Faeroe');
__('Faroe');
__('Jan Mayen');
__('Madeira');
__('Reykjavik');
__('South Georgia');
__('St Helena');
__('Stanley');
__('Australia');
__('ACT');
__('Adelaide');
__('Brisbane');
__('Broken Hill');
__('Canberra');
__('Currie');
__('Darwin');
__('Eucla');
__('Hobart');
__('LHI');
__('Lindeman');
__('Lord Howe');
__('Melbourne');
__('North');
__('NSW');
__('Perth');
__('Queensland');
__('South');
__('Sydney');
__('Tasmania');
__('Victoria');
__('West');
__('Yancowinna');
__('Etc');
__('GMT');
__('GMT+0');
__('GMT+1');
__('GMT+10');
__('GMT+11');
__('GMT+12');
__('GMT+2');
__('GMT+3');
__('GMT+4');
__('GMT+5');
__('GMT+6');
__('GMT+7');
__('GMT+8');
__('GMT+9');
__('GMT-0');
__('GMT-1');
__('GMT-10');
__('GMT-11');
__('GMT-12');
__('GMT-13');
__('GMT-14');
__('GMT-2');
__('GMT-3');
__('GMT-4');
__('GMT-5');
__('GMT-6');
__('GMT-7');
__('GMT-8');
__('GMT-9');
__('GMT0');
__('Greenwich');
__('UCT');
__('Universal');
__('UTC');
__('Zulu');
__('Europe');
__('Amsterdam');
__('Andorra');
__('Athens');
__('Belfast');
__('Belgrade');
__('Berlin');
__('Bratislava');
__('Brussels');
__('Bucharest');
__('Budapest');
__('Chisinau');
__('Copenhagen');
__('Dublin');
__('Gibraltar');
__('Guernsey');
__('Helsinki');
__('Isle of Man');
__('Jersey');
__('Kaliningrad');
__('Kiev');
__('Lisbon');
__('Ljubljana');
__('London');
__('Luxembourg');
__('Madrid');
__('Malta');
__('Mariehamn');
__('Minsk');
__('Monaco');
__('Moscow');
__('Oslo');
__('Paris');
__('Podgorica');
__('Prague');
__('Riga');
__('Rome');
__('Samara');
__('San Marino');
__('Sarajevo');
__('Simferopol');
__('Skopje');
__('Sofia');
__('Stockholm');
__('Tallinn');
__('Tirane');
__('Tiraspol');
__('Uzhgorod');
__('Vaduz');
__('Vatican');
__('Vienna');
__('Vilnius');
__('Volgograd');
__('Warsaw');
__('Zagreb');
__('Zaporozhye');
__('Zurich');
__('Indian');
__('Antananarivo');
__('Chagos');
__('Christmas');
__('Cocos');
__('Comoro');
__('Kerguelen');
__('Mahe');
__('Maldives');
__('Mauritius');
__('Mayotte');
__('Reunion');
__('Pacific');
__('Apia');
__('Auckland');
__('Chatham');
__('Easter');
__('Efate');
__('Enderbury');
__('Fakaofo');
__('Fiji');
__('Funafuti');
__('Galapagos');
__('Gambier');
__('Guadalcanal');
__('Guam');
__('Honolulu');
__('Johnston');
__('Kiritimati');
__('Kosrae');
__('Kwajalein');
__('Majuro');
__('Marquesas');
__('Midway');
__('Nauru');
__('Niue');
__('Norfolk');
__('Noumea');
__('Pago Pago');
__('Palau');
__('Pitcairn');
__('Ponape');
__('Port Moresby');
__('Rarotonga');
__('Saipan');
__('Samoa');
__('Tahiti');
__('Tarawa');
__('Tongatapu');
__('Truk');
__('Wake');
__('Wallis');
__('Yap');
