<?php

define( 'SLIDER_PLUGIN_PATH', plugin_dir_path( __FILE__ ) );

define( 'SLIDER_PLUGIN_DIR_NAME', dirname( plugin_basename( __FILE__ ) ) );

define( 'SLIDER_PLUGIN_PREFIX', 'ssp' ); //Simple Slider Plugin

define( 'SLIDER_PLUGIN_SLIDER_POST_TYPE', SLIDER_PLUGIN_PREFIX . '_slider' );

define( 'SLIDER_PLUGIN_INCLUDE_DIRECTORY_NAME', 'includes' );

define( 'SLIDER_PLUGIN_VIEW_DIRECTORY_NAME', 'views' );

define( 'SLIDER_PLUGIN_CSS_DIRECTORY_NAME', 'css' );

define( 'SLIDER_PLUGIN_JS_DIRECTORY_NAME', 'js' );

define( 'SLIDER_PLUGIN_INCLUDE_DIRECTORY', SLIDER_PLUGIN_PATH .
									  	SLIDER_PLUGIN_INCLUDE_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SLIDER_PLUGIN_VIEW_DIRECTORY', SLIDER_PLUGIN_PATH .
									  	SLIDER_PLUGIN_VIEW_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SLIDER_PLUGIN_CSS_DIRECTORY', SLIDER_PLUGIN_PATH .
									  	SLIDER_PLUGIN_CSS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SLIDER_PLUGIN_JS_DIRECTORY', SLIDER_PLUGIN_PATH .
									  	SLIDER_PLUGIN_JS_DIRECTORY_NAME
							 		  	. DIRECTORY_SEPARATOR );

define( 'SLIDER_PLUGIN_MAIN_FILE', SLIDER_PLUGIN_PATH . 'wp-slider.php' );

define( 'SLIDER_PLUGIN_SLIDER_SHORTCODE', 'slider' );

define( 'SLIDER_PLUGIN_VERSION', '1.0' );