<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
/**
 * This file is generated by Webpack, do not edit it directly.
 */
return [
	'handle' => 'elementor-v2-editor',
	'deps' => [
		'elementor-v2-editor-current-user',
		'elementor-v2-editor-ui',
		'elementor-v2-editor-v1-adapters',
		'elementor-v2-locations',
		'elementor-v2-query',
		'elementor-v2-store',
		'elementor-v2-ui',
		'react',
		'react-dom',
	],
];
